name: get-workflows-id
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    name: JOB_1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"

      - name: get workflows ids
        run: |
          curl \
          -X GET\
          -H "Authorization: Bearer ${{ secrets.TOKEN }}"\
          -H "Accept: application/vnd.github+json"\
          -url "https://api.github.com/repos/eSandrone/multiple_scripts/actions/workflows"
