name: get-workflows-id
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    name: JOB_1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"

      - name: get workflows ids
        run: |
          curl -L \
          -H "Authorization: Bearer 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"\
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/eSandrone/multiple_scripts/actions/workflows
          
          #curl -L \
          # -H "Accept: application/vnd.github+json" \
          # -H "Authorization: Bearer <YOUR-TOKEN>"\
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # https://api.github.com/repos/OWNER/REPO/actions/workflows
