name: Time
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: windows-latest
    outputs:
     time: ${{ steps.time.outputs.st }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute scripts and kill process if necessary
        id: time
        run: |
          #echo "::set-output name=st::$(date +"%s")"
          echo "st=Get-Date" >> $GITHUB_OUTPUT
  job_2:
    runs-on: windows-latest
    needs: job_1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute scripts and kill process if necessary
        id: time
        run: |
          #echo "::set-output name=st::$(date +"%s")"
          echo ${{ needs.job_1.outputs.time }}

#   job_2:
#     runs-on: ubuntu-latest
#     needs: job_1
#     outputs:
#      time: ${{ steps.time.outputs.st }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Execute scripts and kill process if necessary
#         id: time
#         run: |
#           sleep 10
#           echo ${{ needs.job_1.outputs.time }}
#           echo "st=${{ needs.job_1.outputs.time }}" >> $GITHUB_OUTPUT
#   job_3:
#     runs-on: ubuntu-latest
#     needs: job_2
#     outputs:
#      time: ${{ steps.time.outputs.time }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Execute scripts and kill process if necessary
#         id: time
#         run: |
#           echo $(date +"%s")-${{ needs.job_2.outputs.time }}
