name: Wait test
on:
  workflow_dispatch:
jobs:
  time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"

      - name: Execute scripts and kill process if necessary
        run: |
          chmod u+x ./bash/script.sh
          python ./python/wait.py & sleep 10;
          pid_ye=`echo "$!"`
          ps aux | grep -i "wait.py"
          echo $pid_ye
          if pgrep -x "python ./python/wait.py" > /dev/null
          then
            python ./python/message.py
          fi
