name: Wait test
on:
  workflow_dispatch:
jobs:
  time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"

      - name: Execute scripts and kill process if necessary
        run: |
          python ./python/wait.py &
          python ./python/message.py &
          sleep 15 &
          ps aux | grep -i "wait" &
          #echo "$?" &
          #still_up=`echo "$?"` &
          #echo $still_up
          #if [ ps aux | grep -i "message" ] && [ $still_up -eq 1 ]; then echo "Killing process wait.py..."; else echo "Not found"; fi
          if ps aux | grep -i "wait"; then echo "Killing process wait.py..."; else echo "Not found"; fi
