name: test bash list
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    name: JOB_1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test bash list
        run: |
          supported_images="lello1,pino2,pinocc3,res4,e5"
          image="pinocc3"
          IFS=',' read -ra supportedImagesArray <<< "$supported_images"
          for img in "${supportedImagesArray[@]}"
          do
            echo "$img"
            if [[ "$img" == "$image" ]]; then
              echo "IS PRESENT"
            fi
          done
          if printf '%s\0' "${supportedImagesArray[@]}" | grep -Fxqz -- '$image'; then
            echo "IS PRESENT"
          else
            echo "IS NOT PRESENT"
          fi
            
      
