name: test bash list
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    name: JOB_1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test bash list
        run: |
          supported_images="lello1,pino2,pinocc3,res4,e5"
          image="pino"
          isSupported=false
          IFS=',' read -ra supportedImagesArray <<< "$supported_images"
          for img in "${supportedImagesArray[@]}"
          do
            if [[ "$img" == "$image" ]]; then
              isSupported=true
            fi
          done
          if $isSupported
          then
           echo "IS SUPPORTED YEEEE"
          fi

      - name: test replace substing in line 3
        run: |
          str1="linea 3"
          str2="riga 75"
          sed -i '3s/linea 3/riga 75/' ./files/file-test.txt
          cat ./files/file-test.txt
      
