name: test bash list
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    name: JOB_1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test bash list
        run: |
          supported_images="lello1,pino2,pinocc3,res4,e5"
          IFS=',' read -ra supportedImagesArray <<< "$supported_images"
          if [[ ${supportedImagesArray[@]} == "pinocc3," ]]; then
            echo "IS PRESENT"
          else
            echo "IS NOT PRESENT"
          fi
            
      
