# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: trigger

on:
  workflow_dispatch:

jobs:
  repo_disp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: trigger
      run: |
        curl -X POST -H "Authorization: Bearer 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" -H "Accept: application/vnd.github+json" --url "https://api.github.com/repos/eSandrone/multiple_scripts/dispatches" -d "{\"event_type\": \"test\", \"client_payload\":{\"test\": \"TESTTESTTEST\" }}"
