name: w-run
on:
  workflow_run:
   workflows: ["Time"]
   types:
    - completed
jobs:
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"
        
      - name: Try
        run: |
          echo ${{ github.event.workflow_run }}

      - name: Unzip and read
        run: |
          pip install requests
          sudo apt-get install unzip -y
          python ./python/get-logs.py ${{ github.event.workflow_run.id }}
          ls
