name: w-run
on:
  workflow_run:
   workflows: ["Time"]
   types:
    - completed
jobs:
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download logs
        id: time
        uses: actions/github-script@v6
        with:
          script: |         
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "run_id"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/run_id.zip`, Buffer.from(download.data));

      - name: Unzip and read
        run: |
          ls
          unzip run_id.zip
          ls
          cat run_id.txt 
          
            
      

          #echo ${{ github.run_id }}
          #curl -L \
          #eSandrone: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 \
          #-H "Accept: application/vnd.github+json" \
          #--url https://api.github.com/repos/eSandrone/multiple_scripts/actions/runs/${{ needs.job_1.outputs.gj }}/logs
          #ls
