name: w-run
on:
  workflow_run:
   workflows: ["Time"]
   types:
    - completed
permissions: write-all
jobs:
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"
        
      - name: Try
        run: |
          echo ${{ github.event.workflow_run }}
          
          
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "run_id"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/run_id.zip`, Buffer.from(download.data));

      - name: Unzip and read
        run: |
          unzip run_id.zip
          ls
          cat run_id.txt
          #pip install requests
          #sudo apt-get install unzip -y
          #python ./python/get-logs.py ${{ github.event.workflow_run.id }}
          #ls
